### ISSUE TITLE
Trying to schedule default branch fails

### ISSUE THREAD

**Issue by tkhduracell** [bitwit/strider-scheduler#4]
Strider fails to start after I added a daily schedule. 
```
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]: 23105 died 1 null
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at process._tickCallback (node.js:365:13)
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at nextTickCallbackWith0Args (node.js:436:9)
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at /usr/lib/node_modules/strider/node_modules/mongoose/node_modules/kareem/index.js:127:16
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at /usr/lib/node_modules/strider/node_modules/mongoose/node_modules/kareem/index.js:259:21
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at Query.<anonymous> (/usr/lib/node_modules/strider/node_modules/mongoose/lib/model.js:3388:16)
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at /usr/lib/node_modules/strider/node_modules/strider-scheduler/lib/scheduler.js:23:25
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:     at addBranchToSchedule (/usr/lib/node_modules/strider/node_modules/strider-scheduler/lib/scheduler.js:43:121)
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]: TypeError: Cannot read property 'format' of null
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:       ^
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]:       throw er; // Unhandled 'error' event
Nov 19 16:22:11 ubuntu-16-10-x64 strider[22651]: events.js:141
```
Version: `1.1.0`
Strider Version: `1.9.4`
NPM Version: `2.15.11`
Node Version: `4.6.2`

**Comment by tkhduracell** [comment]
@bitwit
